import { Website, AnalyticsSummary, Pageview } from './types';

export const DEMO_WEBSITE: Website = {
  id: 'demo-site-001',
  user_id: 'demo-user',
  name: 'Awesome Startup App',
  domain: 'awesomestartup.io',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const DEMO_WEBSITES: Website[] = [
  DEMO_WEBSITE,
  {
    id: 'demo-site-002',
    user_id: 'demo-user',
    name: 'Personal Portfolio & Blog',
    domain: 'akshay.dev',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const DEMO_PAGEVIEWS: Pageview[] = [
  {
    id: 1,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/',
    path: '/',
    referrer: 'https://news.ycombinator.com',
    visitor_id: 'v-101',
    session_id: 's-101',
    country: 'United States',
    country_code: 'US',
    region: 'California',
    city: 'San Francisco',
    browser: 'Chrome',
    os: 'macOS',
    device_type: 'desktop',
    screen_size: '1920x1080',
    language: 'en-US',
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 2,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/pricing',
    path: '/pricing',
    referrer: 'https://google.com',
    visitor_id: 'v-102',
    session_id: 's-102',
    country: 'India',
    country_code: 'IN',
    region: 'Karnataka',
    city: 'Bengaluru',
    browser: 'Chrome',
    os: 'Windows',
    device_type: 'desktop',
    screen_size: '1440x900',
    language: 'en-IN',
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 3,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/docs',
    path: '/docs',
    referrer: 'https://github.com',
    visitor_id: 'v-103',
    session_id: 's-103',
    country: 'Germany',
    country_code: 'DE',
    region: 'Berlin',
    city: 'Berlin',
    browser: 'Firefox',
    os: 'Linux',
    device_type: 'desktop',
    screen_size: '1920x1080',
    language: 'de-DE',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 4,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/blog/v1-launch',
    path: '/blog/v1-launch',
    referrer: 'https://twitter.com',
    visitor_id: 'v-104',
    session_id: 's-104',
    country: 'United Kingdom',
    country_code: 'GB',
    region: 'England',
    city: 'London',
    browser: 'Safari',
    os: 'iOS',
    device_type: 'mobile',
    screen_size: '390x844',
    language: 'en-GB',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 5,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/',
    path: '/',
    referrer: 'Direct',
    visitor_id: 'v-105',
    session_id: 's-105',
    country: 'Japan',
    country_code: 'JP',
    region: 'Tokyo',
    city: 'Tokyo',
    browser: 'Safari',
    os: 'macOS',
    device_type: 'desktop',
    screen_size: '2560x1440',
    language: 'ja-JP',
    created_at: new Date(Date.now() - 42 * 60000).toISOString(),
  },
  {
    id: 6,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/features',
    path: '/features',
    referrer: 'https://producthunt.com',
    visitor_id: 'v-106',
    session_id: 's-106',
    country: 'Canada',
    country_code: 'CA',
    region: 'Ontario',
    city: 'Toronto',
    browser: 'Edge',
    os: 'Windows',
    device_type: 'desktop',
    screen_size: '1920x1080',
    language: 'en-CA',
    created_at: new Date(Date.now() - 65 * 60000).toISOString(),
  },
  {
    id: 7,
    website_id: 'demo-site-001',
    url: 'https://awesomestartup.io/',
    path: '/',
    referrer: 'https://linkedin.com',
    visitor_id: 'v-107',
    session_id: 's-107',
    country: 'France',
    country_code: 'FR',
    region: 'Île-de-France',
    city: 'Paris',
    browser: 'Chrome',
    os: 'Android',
    device_type: 'mobile',
    screen_size: '412x915',
    language: 'fr-FR',
    created_at: new Date(Date.now() - 95 * 60000).toISOString(),
  },
];

export function getDemoAnalytics(): AnalyticsSummary {
  // Generate 7-day trend
  const chartData = [];
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const baseViews = [1420, 1890, 2390, 2100, 3100, 1950, 2740];
  const baseVisitors = [820, 1100, 1450, 1300, 1850, 1120, 1680];

  for (let i = 0; i < 7; i++) {
    chartData.push({
      date: days[i],
      pageviews: baseViews[i],
      visitors: baseVisitors[i],
    });
  }

  return {
    totalPageviews: 15590,
    uniqueVisitors: 9320,
    topCountry: { country: 'United States', countryCode: 'US', count: 4820 },
    chartData,
    topPages: [
      { path: '/', views: 6420, percentage: 41 },
      { path: '/pricing', views: 3210, percentage: 21 },
      { path: '/docs', views: 2450, percentage: 16 },
      { path: '/blog/v1-launch', views: 1840, percentage: 12 },
      { path: '/features', views: 1100, percentage: 7 },
      { path: '/about', views: 570, percentage: 4 },
    ],
    countries: [
      { country: 'United States', countryCode: 'US', visitors: 4820, percentage: 52 },
      { country: 'India', countryCode: 'IN', visitors: 1950, percentage: 21 },
      { country: 'United Kingdom', countryCode: 'GB', visitors: 890, percentage: 10 },
      { country: 'Germany', countryCode: 'DE', visitors: 640, percentage: 7 },
      { country: 'Japan', countryCode: 'JP', visitors: 420, percentage: 5 },
      { country: 'Canada', countryCode: 'CA', visitors: 350, percentage: 4 },
      { country: 'France', countryCode: 'FR', visitors: 250, percentage: 3 },
    ],
    devices: [
      { device: 'Desktop', count: 6244, percentage: 67 },
      { device: 'Mobile', count: 2796, percentage: 30 },
      { device: 'Tablet', count: 280, percentage: 3 },
    ],
    browsers: [
      { browser: 'Chrome', count: 5780, percentage: 62 },
      { browser: 'Safari', count: 1860, percentage: 20 },
      { browser: 'Firefox', count: 930, percentage: 10 },
      { browser: 'Edge', count: 560, percentage: 6 },
      { browser: 'Other', count: 190, percentage: 2 },
    ],
    referrers: [
      { referrer: 'Direct / None', count: 3728, percentage: 40 },
      { referrer: 'google.com', count: 2330, percentage: 25 },
      { referrer: 'news.ycombinator.com', count: 1398, percentage: 15 },
      { referrer: 'github.com', count: 932, percentage: 10 },
      { referrer: 'twitter.com', count: 559, percentage: 6 },
      { referrer: 'producthunt.com', count: 373, percentage: 4 },
    ],
    recentVisits: DEMO_PAGEVIEWS,
  };
}
